### ISSUE TITLE
Problem with Gantry and/ or sensorless homing

### ISSUE THREAD

**Issue by PDotStrong** [rdudhagra/Sand-Table#42]
I changed the size of the ganrty in the .env file in 500x500 mm but at start it moved always on new spots an the carrier stops never in the middle. How shoild the gantry / carrier behave at server start?

and sry xD for alle issues

**Comment by rdudhagra** [comment]
haha no worries! So when you turn the table on:
(1) The gantry will move all the way to the left on one axis
(2) The gantry will move all the way down on the other axis
(3) The gantry will move diagonally to the center of the table

Since your table is a different size from mine you'll need to change the dimensions in `.env` as you mentioned AND reflash the Marlin firmware with the new dimensions (you'll have to modify `Configuration.h`, specifically [these lines](https://github.com/rdudhagra/Sand-Table/blob/f8876251e55bee3187eb94d0f94dd297293fad03/Marlin-2.0.x/Marlin/Configuration.h#L1095)).

**Comment by PDotStrong** [comment]
Hi :) I changed the size on your mentioned spots, but nothing changed really… I will check the hardware for sensorless homing again…  Video is made

**Comment by PDotStrong** [comment]
![image](https://user-images.githubusercontent.com/129870639/234777208-da600261-9a4b-46d9-bfb3-629b5de79806.jpg)

**Comment by PDotStrong** [comment]
![Uploading image.jpg…]()

**Comment by PDotStrong** [comment]
![image](https://user-images.githubusercontent.com/129870639/234777422-afb3dfae-8bf1-43f5-b7ee-810d60b930da.jpg)

**Comment by PDotStrong** [comment]
![image](https://user-images.githubusercontent.com/129870639/234777600-03224c3a-f26e-40d7-ae5e-b72141905d05.jpg)

**Comment by PDotStrong** [comment]
https://user-images.githubusercontent.com/129870639/234777829-ea4fcb3a-b8f5-4ee5-8cdf-293d84c7512f.mov

**Comment by PDotStrong** [comment]
I got it! THANK YOU =)

**Comment by PDotStrong** [comment]
When i change the parametrs in configuration.h and uploaded it and the change the values of x and y in the .env files. have I something to make that the change get refreshed in the machine?

**Comment by rdudhagra** [comment]
Not sure what you mean exactly but you do need to restart the webserver to refresh changes in `.env`.
